name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'   # Match your local PHP version

      # Step 3: Install dependencies using Composer
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Step 4: Set PHPUnit as Executable
      - name: Set PHPUnit as Executable
        run: chmod +x vendor/bin/phpunit

      # Step 5: Run PHPUnit tests
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml
